### ISSUE TITLE
PMD throws false-positive CloseResource violations

### ISSUE THREAD

**Issue by ImSpaceLover** [BasePractice/algorithms-and-data-structures-2024#13]
PMD sends a message saying "Ensure that resources like this InputStream object are closed after use", even though Scanner is already closing
Here's the piece of code where it finds the error:
```
        int i = 0;
        try {
            while (i < arr.length) {
                arr[i] = sc.nextFloat();
                i+=1;
                }
            } catch (RuntimeException e) {
            throw new RuntimeException(e);
        }
        finally {
            sc.close();
        }
```
---
PMD отправляет сообщение со словами "Ensure that resources like this InputStream object are closed after use", хотя Сканнер уже закрывается
Сверху часть кода, где он находит ошибку

-- Студент МИРЭА

**Comment by Pastor** [comment]
Используйте конструкцию `try-with-resources`
