### ISSUE TITLE
Java Build Error

### ISSUE THREAD

**Issue by Kr1sM0L** [BasePractice/algorithms-and-data-structures-2024#137]
Можно спросить, а в чём заключается эта ошибка в Java Build
![image](https://github.com/user-attachments/assets/cc18da59-4db7-4083-a0a6-1a7a32044054)

#134

**Comment by Pastor** [comment]
Локально сборка проходит всего проекта? не только вашего модуля, а всего проекта

**Comment by Kr1sM0L** [comment]
Здравствуйте, да сборка всего проекта локально проходит
![image](https://github.com/user-attachments/assets/2c2b5103-9027-4efa-95ac-1ee5576cdcc6)

**Comment by Pastor** [comment]
Попробуйте обновить репозиторий и пересоздать PR
